name: Lucas Gatsas
description: I'm a Ui/Ux Designer & Front End Engineer 
meta_description: "Lucas Gatsas Front End Engineer"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'http://spaceg.github.io'
google_analytics: 'UA-98626242-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://spaceg.github.io'
author:         'Lucas Gatsas'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
