# Site settings
title: Lucas Gatsas
email: l.gatsas33@gmail.com
description: "Hello, my Name is Lucas Gatsas"
baseurl: ""
url: "https://spaceg.github.io"
twitter_username: LucasGatsas
github_username:  spaceg
google_username:  https://plus.google.com/101826267816845608605/posts

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
