# Site settings Update for my Blog : spaceg.github.io Do.9.April 15.49:24 2015 Update Mo.29.Juni 00:17:28  
title: l.g
email: lucasgatsas@gmail.com
description: "Hello, My Name is Lucas Gatsas, I'm a Front End Engineer, Web Developer Sys Admin from St. Gallen, Switzerland. My Skills are HTML/HTML5, CSS/CSS3, LESS/SASS, Javascript (DOM), jQuery, PHP/MYSQL, RUBY/RAILS. Hallo, mein Name ist Lucas Gatsas, komme aus St. Gallen, Schweiz. Ich entwickle Websiten Groos oder Klein. "
baseurl: ""
url: "http://lucasgatsas.ch"
twitter_username: LucasGatsas
github_username:  spaceg
google_username:  https://plus.google.com/101826267816845608605/posts
instagram_username:  lucasgatsas
angelList_username:  lucas-gatsas


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 0 #posts per page

